apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-testing-non-jpa-k8s-deployment
  labels:
    app: docker-testing-non-jpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-testing-non-jpa
  template:
    metadata:
      labels:
        app: docker-testing-non-jpa
    spec:
      containers:
      - name: springboot-testing
        image: shologuanda/docker-testing-non-jpa:latest
        ports:
        - containerPort: 9090 
        
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: docker-testing-non-jpa-k8s-svc
spec:
  selector:
    app: docker-testing-non-jpa
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.
